### ISSUE TITLE
train-test split 

### ISSUE THREAD

**Issue by plarmuseau** [rupinas/LAPINE#2]
Hello
if you split the train dataset in an train/test with

    X_train, X_test, y_train, y_test = train_test_split( embeddings, Y, test_size=0.33, random_state=42)

what is the clf.score(X_test,y_test) ?

**Comment by rupinas** [comment]
It is the prediction step with a classifier.

Details are well described in the following link.
https://scikit-learn.org/stable/

**Comment by rupinas** [comment]
> Hello if you split the train dataset in an train/test with
> 
> ```
> X_train, X_test, y_train, y_test = train_test_split( embeddings, Y, test_size=0.33, random_state=42)
> ```
> 
> what is the clf.score(X_test,y_test) ?

It is the prediction step with a classifier.

Details are well described in the following link.
https://scikit-learn.org/stable/
